# Generated by Django 4.2.16 on 2024-12-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chess_App", "0002_playergame"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invite",
            old_name="sent_at",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="playergame",
            unique_together=set(),
        ),
    ]
