# Generated by Django 4.2.16 on 2024-12-03 22:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Chess_App", "0003_rename_sent_at_invite_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invite",
            old_name="created_at",
            new_name="sent_at",
        ),
        migrations.AlterUniqueTogether(
            name="playergame",
            unique_together={("user", "game")},
        ),
    ]
